### ISSUE TITLE
SelectAll extension

### ISSUE THREAD

**Issue by wyuenho** [wyuenho/backgrid#18]
Provide an extension that offers a special cell type that isn't connected to the model, but instead sends an event containing the model such that further actions can be performs on the handlers.

**Comment by bargaorobalo** [comment]
@antonyraj I don't know if it still important to you(almost 3 years later), but I have a similar feature and I did an extension from `SelectRowCell`:

```
cell: Backgrid.Extension.SelectRowCell.extend({
    render: function(){
        if(this.model.get('my-funny-property')){
             this.$el.empty().append('<input type="checkbox" class="whatever-you-need"/>');
        }
        this.delegateEvents();
        return this;
   }
})
```

I'm still using the version 0.2.0 :sweat_smile:
