### ISSUE TITLE
Filter AND Pagination not working together

### ISSUE THREAD

**Issue by carlygeehr** [wyuenho/backgrid#183]
I'm having a problem where I can get pagination and filtering to work fine independently of one another - but then when I combine them, filtering stops working. It's hard for me to tell what it's actually doing - the table changes as you type, but not in any kind of useful way.

Here's a plunker: http://plnkr.co/edit/rTUxEurrXsMxCTPiMYaw?p=preview
It's set to filter on the "owner" column. If you comment out the 'mode: "client"' line in manager.js, the filtering works just fine (but of course the pagination no longer works).

Any ideas?

**Comment by ashishghimire** [comment]
@wyuenho please help with the issue addressed here:
http://stackoverflow.com/questions/32955977/backgrid-paginator-is-not-working-after-collection-filter
