### ISSUE TITLE
Cut and paste rows in Backgrid? 

### ISSUE THREAD

**Issue by ptaccount** [wyuenho/backgrid#206]
Is it possible to cut and paste rows in backgrid ? 
Any hint how it could be done ....

Thanks,
pt

**Comment by gloomytree** [comment]
Can i reopen this? 

I would like to have an empty row at the bottom of the grid where you can paste in data, like from a csv file or an excel sheet. Possibly multiple rows at once.

How can this be achieved? What is to be considered when read-only cells are present, like the ID Cell?
