### ISSUE TITLE
add a new row - working example?

### ISSUE THREAD

**Issue by brandonscript** [wyuenho/backgrid#241]
Forgive me for asking this (I know it's in the FAQ and has been asked several times already)

There's no working example of a simple add row button. The instructions simply say to use `grid.insertRow`

That's not enough information; is there a working example of a button adding an empty row? (jsFiddle or something?) How would I wrap this in a separate function (say an `onClick` button function)

```
function addRow()
{
    //stuff happens here
}

//below this line is my grid creation and init
```

**Comment by amiceli** [comment]
@r3mus when I add a row with insertRow I don't see it on the grid that's normal ?
