### ISSUE TITLE
CSS issue in IE10 in editor mode

### ISSUE THREAD

**Issue by JoshClose** [wyuenho/backgrid#258]
The text is cutoff in editor mode.

![image](https://f.cloud.github.com/assets/114971/717518/c7a00b84-df4e-11e2-853f-2b4b9b869d3b.png)

**Comment by ntodorov** [comment]
I see similar cutoff in Chrome Version 53.0.2783.4 dev-m (64-bit)
![6-30-2016 9-30-26 am](https://cloud.githubusercontent.com/assets/4613148/16494107/578e5c74-3ea5-11e6-8b39-00feef3d8852.png)
