### ISSUE TITLE
Displaying Nested Attributes of Models as Rows

### ISSUE THREAD

**Issue by theaeolianmachine** [wyuenho/backgrid#265]
Hey,

First off, it's a really sweet library. We were using DataTables for a project
a while back, but right now we're experimenting with using Backbone.js. Here's
what my model basically looks like.

```
    TopLevelModel
    {
        name: 'Hello World',
        dependentModels: [{
            depAttribute: 'myAttribute,
            depAttribute2: 'myAttribute,
            depAttribute3: 'myAttribute
        }, {
            depAttribute: 'myAttribute,
            depAttribute2: 'myAttribute,
            depAttribute3: 'myAttribute
        }]
    }
```

There are two tables: one that shows `name`, `dependentModels.length`, and a
delete button that deletes the row. That works just fine with a bit of
extending Backgrid.CellFormatter and Backgrid.Cell.

However, the second table is supposed to show all of the `dependentModels` and
their attributes as columns. I don't want these to be represented as Backbone
models, because it's already denormalized on the server for several reasons,
and tracking which ones go with which TopLevelModel is a bit of a pain.
Honestly, we're cool with just refreshing the dependentModel table every time a
TopLevelModel is deleted from its collection.

Given this, do you have any suggestions on where to extend the API's? It seems
pretty instilled that one row == one model in DataGrid, and I'd really like to
not abandon the library. DataTables didn't enjoy with Backbone earlier much,
and Backgrid works so well with the first table. Any ideas would be appreciated
before I rip the guts of this open :).

**Comment by sprugman** [comment]
> There are also a number of third-party plugins for Backgrid that supports subgrids.

Is there a list of those somewhere?
