### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by terinjokes** [wyuenho/backgrid#289]
Now that you've removed builds from the repository, would you be interested in publishing the builds to npm? This wouldn't require you to see a bunch of red in your `git status`, and still allow browserify to work "out of the box" with backgrid, rather than require us run a build and publish internally.

**Comment by lzrski** [comment]
Hi @terinjokes . I'm using NPM module published by you without any problem. Thanks for your work here.

However I'd like to use latest functionality of `wyuenho/backgrid:master` (brought by commits past 0.3.5 release, especially 2c30b05). I wonder what's the best approach here. Would it be possible to just merge your `terinjokes/backgrid:npm` branch with `wyuenho/backgrid:master`? If so, wouldn't we all benefit from merging it?

@wyuenho Thanks for Backgrid. It's awesome!
