### ISSUE TITLE
[Q.] how to implement extra info view for every record 

### ISSUE THREAD

**Issue by hardevine** [wyuenho/backgrid#306]
i want to have a extra view for every record which would be dynamic and would have jquery tabs plugin. should i have to change on render method for every row.?
something like Datatables example 
https://datatables.net/release-datatables/examples/api/row_details.html

**Comment by Warlord099** [comment]
But how would I do something like this if I wanted the extra rows to be expanded by default? I tried doing it in the row render, but it fails because the element isn't yet added to the DOM.

**Comment by Warlord099** [comment]
I ended up coming across the "DOMNodeInserted" event and using that on the element inside the row render. If there is a better way let me know.
