### ISSUE TITLE
[question] Add filter to the every column

### ISSUE THREAD

**Issue by terales** [wyuenho/backgrid#409]
I have to add filter for each column like this: Filter for each column in Backgrid

![Achieve this](https://f.cloud.github.com/assets/1920639/1809015/777f6c4a-6d9b-11e3-91eb-2683eb1757f4.png)

But I can't understand how should I extend Backgrid.Header to achieve this. Can you point me to the right direction?

**Comment by irraju** [comment]
@terales This feature is part of which plugin?

**Comment by terales** [comment]
@irraju, this feature wasn't implemented in project.

**Comment by phillipsnick** [comment]
@terales did you ever build an extension to handle this? 

Currently experimenting with a few things and curious how others may have handled this feature.

**Comment by terales** [comment]
@phillipsnick no, i didn't. We walked away from tables on that project :smile:
