### ISSUE TITLE
Grid.sort doesn't reset previously sorted column's sort caret on grids using pageable

### ISSUE THREAD

**Issue by wyuenho** [wyuenho/backgrid#429]
Steps to reproduce:
1. go backgridjs.com
2. open the console
3. pageableGrid.sort("name", "descending");
4. pageableGrid.sort("pop", "ascending");
5. name's sort caret is still in descending order

Expected behavior:

name's sort caret should not be displayed and the column's direction shouldn't be null.

**Comment by andrefrcastro** [comment]
I'm still experiencing this.
Have latest version of backgrid and all dependencies (via bower).

I'm using:

* backgrid
* backgrid-text-cell
* backbone-pageable
* backgrid-paginator
* backgrid-moment-cell
* backgrid-select-all
* backgrid-filter
