### ISSUE TITLE
Add full support for AMD (without shim)

### ISSUE THREAD

**Issue by twalker** [wyuenho/backgrid#448]
Backbone v1.1.1 [now supports AMD](http://backbonejs.org/#changelog).
When using an AMD shimmed Backgrid with Backbone v1.1.1, I get this error.

```
  var $ = Backbone.$;
```

throws a `Cannot read property $ of undefined` error.

It'd be great if Backgrid fully supported AMD.

I believe the `returnExports` or `returnExportsGlobal` [UMD pattern](https://github.com/umdjs/umd) would probably work.

ES6 Modules can't come soon enough.

**Comment by kvslee** [comment]
Can I add backgrid-object-cell via NPM package?
