### ISSUE TITLE
renderable: false not working on 0.3.5?

### ISSUE THREAD

**Issue by brandonscript** [wyuenho/backgrid#459]
I just upgraded a backgrid implementation to 0.3.5 - using `renderable: false` on column definitions doesn't seem to work anymore? No errors appear in the console though. Let me know if you need more info.

**Comment by Naveen2605** [comment]
Same issue: i have updated backgrid to 3.5 version, existing functionality got distrubed with new version renderable : false configuration is not working anymore, can you please tell me an alternate config to resolve this.

**Comment by Naveen2605** [comment]
After taking new update of backgrid (ver 3.5) previous attributes and orginal attributes of model are not getting updated its an big issue, i am checking it at backgrid: edited event is fired and comparing both model.attributes and model._previoustAttributes it not getting updated, In previous version it worked well 
can you please help me with this sissue @wyuenho

**Comment by bam931** [comment]
Maybe you are using some library, like bootstrap, which rewrite classes of table elements. 
I tried write `renderable: false` but columns was rendered. When i removed botstrap classes like `table, table-bordered, etc` i resolved the problem

**Comment by faroukellouze** [comment]
replace the render function of the `Row ` variable in your backgrid.js by this one
 ` render: function () {
    this.$el.empty();

    var fragment = document.createDocumentFragment();
    for (var i = 0; i < this.cells.length; i++) {
      fragment.appendChild(this.cells[i].render().el);
       if (!this.cells[i].column.get("renderable"))
                    this.cells[i].$el.hide();
    }

    this.el.appendChild(fragment);

    this.delegateEvents();

    return this;
  },`

it will work just fine
