### ISSUE TITLE
How to custom the Backgrid.Extension.PageHandle

### ISSUE THREAD

**Issue by kim2014** [wyuenho/backgrid#474]
I configure my pageSize=10 and totalPages=10. So each time I fetch 100 records from database. So if someone clicks page #10(last page) then ">" , ">>" is disable. 
Instead of disable (> and >>) I want these two are still active and if someone clicks on either > or >> then I want fetch next 100 records in the database.

 Can we custom the Backgrid.Extension.PageHandle to do this? Because of performance reasons I don't want to fetch a lot of records in the database at once.  Great appreciate If you can give some directions how to custom PageHandle to fetch more records from database then someone clicks on > or >> on the last page.
Thanks,
JP
Rewind( <<) ; back ( <) ; forward ( >)  and fastForward() >>

**Comment by Muthukumar28041990** [comment]
Hi Kim,
    I have the same requirement as yours.
                In my application, I ll get 100 items of data initially from the service, when I click on the last pagination number say 10 , I need to make another service call to fetch next 100 items, How to go with the logics.

How to find whether I have reached the last page?

Thanks in Advance.
Muthu
