### ISSUE TITLE
ClientSideFilter: filters for more columns simultaneously

### ISSUE THREAD

**Issue by StefanoSega** [wyuenho/backgrid#518]
Hallo!

I've this issue:
I have a BackGrid with 2 visible columns ("Username" and "Active state", the last one is a boolean column) and I want to create client-side filters for both the columns, so a textbox for "Username" and a Bootstrap CSS Radiobutton Group for the "Active state".

The problem is:
if I put both the columns in the same filter only one single text field will appear:

```
       var filter = new Backgrid.Extension.ClientSideFilter({
            collection: pageableUsers,
            fields: ['UserName', 'Active']
        });
        $("#divSearch").append(filter.render().el);
```

... while if I create two distinct filters they'll be automatically embedded inside different forms so e.g. if I've filtered the rows writing "Mark" inside the "Username" textbox and then I write "true" inside rhe "Active" textbox the previous filter on the "Username" textbox will have no more effect losing the filter on the rows with "Mark" in the "Username" field:

```
       var filter_username = new Backgrid.Extension.ClientSideFilter({
            collection: pageableUsers,
            fields: ['UserName']
        });
        $("#divSearch").append(filter_username.render().el);
        var filter_active = new Backgrid.Extension.ClientSideFilter({
            collection: pageableUsers,
            fields: ['Active']
        });
        $("#divSearch").append(filter_active.render().el);
```

so:
is there a way to make two different filters to apply on the same collection with logic operator "and" between the two filters?

Thank you,
Futourism

**Comment by helenler** [comment]
please show your codes that it makes two different filters to apply on the same collection with logic operator "and" between the two filters.
