### ISSUE TITLE
jQuery reference

### ISSUE THREAD

**Issue by Integral** [wyuenho/backgrid#533]
Hey!
There're places like [this](https://github.com/wyuenho/backgrid/blob/master/lib/backgrid.js#L2148), where $ is undefined after installing through NPM.
I saw some pull requests, like [this](https://github.com/wyuenho/backgrid/pull/61), which must solved this problem. But it seems that it dropped now. Any workarounds here?

**Comment by wyuenho** [comment]
Backgrid doesn't have a hard dependency on jquery. It has a hard dependency on backbone, which also has no hard dependency on jquery. Just set `Backbone.$ = require('jquery')` somewhere in your code base.
