### ISSUE TITLE
unshift not working with cell formatter?

### ISSUE THREAD

**Issue by brandonscript** [wyuenho/backgrid#553]
I've been using this cell formatter for a while - it works great to uppercase the display name of a column's values:

    ...
    formatter: _.extend({}, Backgrid.CellFormatter.prototype, {
      fromRaw: function (rawValue) {
        return rawValue.toUpperCase();
      }
    }),
    ...

Until now, I've been using:

	model.add([{
		name: "somename",
		text: "",
		comments: ""
	}]);

And this too works just fine when using `.add`. I'm trying to use `.unshift` however, and now it doesn't work, throwing an error that you can't call `.toUpperCase()` on undefined -- leading me to determine that `rawValue` in the formatter is undefined. 

How can I get the formatter to work with unshift?

**Comment by wyuenho** [comment]
A javascript array doesn't trigger any events, if you want to add a row on top of the grid, just call `Collection.add`.
