### ISSUE TITLE
BooleanCellEditor initially needs to be clicked twice

### ISSUE THREAD

**Issue by dexygen** [wyuenho/backgrid#557]
Whether the value is true or false (and therefore the Boolean cell is checked or unchecked), in order to initially edit a boolean cell, one must click twice to make the first edit.  Its as though the first click merely enables editing (not unlike the first click in an InputCellEditor) whereas to me it seems natural that for the BooleanCellEditor, *any* click will toggle the state from checked to unchecked, even the first click.  Thanks in advance.

**Comment by dexygen** [comment]
I extended BooleanCell as follows and it correctly toggles the checkbox state when entering edit mode, but the mystery (to me at least) is why the checkbox doesn't get toggled in the first place.  Anyway hope this helps someone (or perhaps gets baked into the core?)

        var MLBooleanCell = Backgrid.BooleanCell.extend({
            enterEditMode: function () {
                Backgrid.BooleanCell.prototype.enterEditMode.apply(this, arguments);
                var checkbox = this.$('input');
                checkbox.prop('checked', !checkbox.prop('checked'));
            }
        });

**Comment by dexygen** [comment]
My "solution" above does not work properly, it toggles *every* checkbox in the column when any single one is checked

**Comment by dexygen** [comment]
I stumbled upon the following, I was just setting up to do more stuff on click, but this no-op function actually does the trick for some reason (perhaps not unlike a defer?)

    var BooleanCell = Backgrid.BooleanCell.extend({
        events: _.extend(Backgrid.BooleanCell.prototype.events, {
            "click": function () {}
        })
    });

**Comment by machineghost** [comment]
I'm having the same issue. Thanks for the possible workaround @dexygen, but If possible an official fix to this issue would be nice.

**Comment by wyuenho** [comment]
When you are tabbing across cells, it only makes sense to separate the focus and edit actions. This is the same for all cell types for consistencies. However you do it will only break keyboard navigation.
