### ISSUE TITLE
underscore dependency in bower.json

### ISSUE THREAD

**Issue by cybernetlab** [wyuenho/backgrid#559]
Hi!
Is where any reason to fix underscore dependency to 1.5.x in `bower.json`? Can I safetly use 1.6.x? I think that `>=1.5.2` looks reasonable than `~1.5.2` that requires users to have old 1.5.x undescore library.
Thanks

**Comment by christinedraper** [comment]
I am using underscore 1.7 (with jquery 2.1.3 and backbone 1.1.2).  I had some problems getting those levels to work with requireJS (AMD support gets introduced in underscore 1.6 and backbone 1.1.1) - there are some issues to do with a non-AMD module calling AMD-enabled modules - so I would advise caution, at least if you are using requireJS.

I finally got my use case working by removing the underscore and backbone shims, and specifying "wrapShim: true" 
https://github.com/jrburke/r.js/blob/b8a6982d2923ae8389355edaa50d2b7f8065a01a/build/example.build.js#L68
but I cant vouch for the robustness of this answer.

**Comment by cybernetlab** [comment]
@christinedraper Thanks, but I'm using backgrid and other libraries without requireJS.

So, when I manually load all my libraries via `<script>` underscore 1.6 and 1.7 works well with current backgrid. But when I use [rails-assets](https://rails-assets.org/) system that builds assets based on `bower.json` this requires me to use undersocre 1.5.2 and this version is so old for other dependencies (for marionette for example). And having two versions of underscore is bad idea.

**Comment by wyuenho** [comment]
It supports 1.8+ now
