### ISSUE TITLE
Extending Grid with custom row doesn't retain custom row.

### ISSUE THREAD

**Issue by jacobcase** [wyuenho/backgrid#561]
When extending the Grid class, you can pass the columns in, which was fixed in an earlier bug fix, but you cannot yet do that with a custom row.  I feel this is important, because when you store your Views in a variable, like app.views, you don't need to store a variable for your custom row that you only need to define for that one extended View class but still have to pass it in every time you create a new instance.

**Comment by wyuenho** [comment]
Fixed by https://github.com/wyuenho/backgrid/pull/562
