### ISSUE TITLE
Can't handle format from Parse object with Date DataType

### ISSUE THREAD

**Issue by reidsheppard** [wyuenho/backgrid#570]
I am using objects from Parse.com to populate into a Backgrid Table.

The date format is the following.
Sat Jul 20 2013 00:00:00 GMT-0400 (EDT)

However Backgrid can't recognize this a a date, it only works as a string.  I have tried the DateCell, DateTimeCell but only string type works.  The specific error occurs in this snippet.

This line from the snippet below, fails with this error Uncaught TypeError: undefined is not a function backgrid.js line 453.
 data = data.trim();

This method
DatetimeFormatter.prototype = new CellFormatter();
_.extend(DatetimeFormatter.prototype, {

if (_.isNumber(data)) {
      var jsDate = new Date(data);
      date = lpad(jsDate.getUTCFullYear(), 4, 0) + '-' + lpad(jsDate.getUTCMonth() + 1, 2, 0) + '-' + lpad(jsDate.getUTCDate(), 2, 0);
      time = lpad(jsDate.getUTCHours(), 2, 0) + ':' + lpad(jsDate.getUTCMinutes(), 2, 0) + ':' + lpad(jsDate.getUTCSeconds(), 2, 0);
    }
    else {
      data = data.trim();
      var parts = data.split(this.ISO_SPLITTER_RE) || [];
      date = this.DATE_RE.test(parts[0]) ? parts[0] : '';
      time = date && parts[1] ? parts[1] : this.TIME_RE.test(parts[0]) ? parts[0] : '';
    }

It would really suck to have to write my own string parser for this, but maybe I can do that with existing cell types.

**Comment by reidsheppard** [comment]
I was able to work around the issue by doing the following.  I basically wrote my own parser for the date.  I don't fully understand why the default date cell can't handle the format though, might be a bug.


name: "baselineDate",
            label: "Date",
            cell: "date",
            formatter: _.extend({}, Backgrid.CellFormatter.prototype, {
                fromRaw: function (rawValue, model) {
                    return (model.get("baselineDate").getMonth() + 1) + "/" + (model.get("baselineDate").getDate() + "/") +  model.get("baselineDate").getFullYear();
                }
            })

**Comment by wyuenho** [comment]
Parse is dead so I'm closing this one.
