### ISSUE TITLE
previous attributes, orginal attributes not getting updated in version 3.5

### ISSUE THREAD

**Issue by Naveen2605** [wyuenho/backgrid#572]
After taking new update of backgrid (ver 3.5) previous attributes and orginal attributes of model are not getting updated its an big issue, i am checking it at backgrid: edited event is fired and comparing both model.attributes and model._previoustAttributes it not getting updated, In previous version it worked well 
can you please help me with this sissue @wyuenho

**Comment by wyuenho** [comment]
Closing for being stale
