### ISSUE TITLE
Column Chooser for backgrid

### ISSUE THREAD

**Issue by vgodly** [wyuenho/backgrid#574]
I am new to backgrid and I am curious if there is any column chooser for backgrid so that user can choose what columns are to be visible in my grid after grid render. 

Lets say I have hidden a few columns using renderable:false while grid render. But I planning to give an option to user to choose from all the columns what columns he wants to see and update the grid accordingly. 

I don't want to render the grid again by changing renderable property of the columns. Can we do this without grid re-render similar to jqqrid column chooser

**Comment by excentris** [comment]
@vgodly You could take a look at the [Backgrid.ColumnManager](https://github.com/WRidder/Backgrid.ColumnManager) plugin ([demo](https://wridder.github.io/backgrid-demo/)).

**Comment by vgodly** [comment]
Thanks @excentris  . Will have a look on the same :+1:
