### ISSUE TITLE
NPM/CommonJS + jQuery requirement broken

### ISSUE THREAD

**Issue by ryno1234** [wyuenho/backgrid#576]
First off, thanks for the great tool, much appreciated!

Backgrid uses Backbone.$ to access jQuery, however Backbone does not require jQuery and thus by default (when used in an NPM/CommonJS build) this property is empty and Backgrid bombs. If Backgrid requires jQuery, why doesn't Backgrid simply require that dependency itself versus attempting to get it from another module (Backbone) which doesn't mandate it?

Thank you

**Comment by ryno1234** [comment]
I was going to fix this issue and submit a pull request but it seems that the latest NPM version published is not the same version here. Where can I find the latest version in GitHub?

**Comment by wyuenho** [comment]
This should have been fixed a long time ago. Please try 0.3.7
