### ISSUE TITLE
Add classname to certain th-element

### ISSUE THREAD

**Issue by crebuh** [wyuenho/backgrid#583]
Is there a possibility to add a certain classname (e.g. hidden-xs) to a certain th element. 

For example I've defined a column schema like

```
{
            name: 'billingdate', // The key of the model attribute
            label: 'Billingdate', // The name to display in the header
            editable: false, // By default every cell in a column is editable, but *ID* shouldn't be
            classname: 'hidden-xs'
            cell: 'string'
}
```

now the hidden-xs class is added to all of these tds in my grid. But what could i do to add the classname also to the th above those tds?

A workaround would be to work with the css, because to each th the name of the attribute is also added as classname (in this example billingdate). It would also work, but would need much more custom css styles.

**Comment by luishdez** [comment]
You can extend the header cell

```
  {
    name: "field",
    headerCell: Backgrid.HeaderCell.extend({
      tagName: 'th class="width"'
    }),
    cell: 'integer'
  },
```

**Comment by wyuenho** [comment]
```javascript
{
    name: "field",
    headerCell: Backgrid.HeaderCell.extend({
        className: 'whatever you want'
    }),
    cell: 'integer'
  },
```
