### ISSUE TITLE
Click event at view ?

### ISSUE THREAD

**Issue by Arti3DPlayer** [wyuenho/backgrid#587]
can i add events at Grid class like this:
```
var invoice_grid = new Backgrid.Grid({
            events: {
                "click #mark_paid": "open"
            },
            open: function () {
                alert('asldkfjal;sdkf')
            },});
```

**Comment by insanity54** [comment]
I would also like to know

**Comment by wyuenho** [comment]
Just inherit the Grid and add your own events. Every component in Backgrid is just a Backbone.View

**Comment by millerbryan** [comment]
> Every component in Backgrid is just a Backbone.View

That is a huge and very helpful fact!  It would be good to state that on the Backgid home page.  I was trying to create Grid components inside Backbone views and wondering why I was seeing odd behaviour.
