### ISSUE TITLE
backgrid-filter doesn't search through formatted content

### ISSUE THREAD

**Issue by Industrial** [wyuenho/backgrid#590]
Hi.

I want to use both backgrid-filter and custom formatters. I have a deep nested object and I want to display some deep properties in the table.

`backgrid-filter` only searches through properties, not actual formatted column values.

For now, I'm going to have to do the formatting beforehand, not using the backgrid formatters, to be able to use the filter :-)

**Comment by aliabdzad** [comment]
i have the same problem ... any one can help ? @wyuenho

**Comment by Devtr0n** [comment]
It is because the filter only works on the underlying collection, not the rendered output.

Is it possible you can control the data before it gets to the collection in the UI?

**Comment by wyuenho** [comment]
You can extend the filter classes and override the event hash.

https://github.com/wyuenho/backgrid-filter/blob/master/backgrid-filter.js#L57-L61
