### ISSUE TITLE
Add tooltip for th

### ISSUE THREAD

**Issue by crebuh** [wyuenho/backgrid#592]
Hi,

is there a possibility to add a tooltip to each of the th's in the table head? 

Sometimes grid can become very big with a lot of columns. Due to that, we often use really short labels in the table head. But sometimes there are not self-explaining. So it would be great to add a tooltip, to explain what the purpose of each column is.

**Comment by tsjoberg** [comment]
If you look at the header docs here:

http://backgridjs.com/ref/header.html

You can use your own custom HeaderCell and overwrite the render method to do your tooltip implementation.

http://wyuenho.github.io/backgrid/api/index.html#!/api/Backgrid.HeaderCell

````javascript
var ToolTipHeaderCell = Backgrid.HeaderCell.extend({
  render : function() {
       //Example Bootstrap Tooltip Implementation - but this is where you put your tooltip implementation
       this.$el.tooltip({
	    title: this.column.get('fullDescription'), //render has access to the column attributes here
	    container: 'body'
       });
  }
});

var grid = new Backgrid.Grid({

  columns: [{
    name: "modelAttribute",
    label: "shortDescription",
    cell: "string",
    fullDescription: "My tooltip description",
    headerCell: ToolTipHeaderCell
  }],

  collection: col
});
````

**Comment by wyuenho** [comment]
Just override `HeaderCell:render` and put the title attribute into the `th`.

```javascript
var grid = Backgrid.Grid({
  headerCell: Backgrid.HeaderCell.extend({
    render: function() {
      Backgrid.HeaderCell.prototype.render.apply(this, arguments);
      this.$el.attr('title', this.column.get('label'));
      // optionally, if you use bootstrap
      this.$el.tooltip();
      return this;
    }
  })
});
```

**Comment by madkinder** [comment]
Unfortunately the code above doesn't work as is. `Backgrid.Grid` [doesn't pass](https://github.com/wyuenho/backgrid/blob/624745c9d8049788a5aaa28e01a902b19e16e8a1/src/header.js#L200-L203) `headerCell` option to `Backgrid.HeaderRow`'s constructor. Therefore `options.headerCell` [here](https://github.com/wyuenho/backgrid/blob/624745c9d8049788a5aaa28e01a902b19e16e8a1/src/header.js#L162) is always `undefined`.

This is my quick and dirty adaptation of the code above:

```javascript
var grid = Backgrid.Grid({
  header: Backgrid.Header.extend({
    initialize: function (options) {
      this.columns = options.columns;
      if (!(this.columns instanceof Backbone.Collection)) {
        this.columns = new Columns(this.columns);
      } 

      this.row = new Backgrid.HeaderRow({
        headerCell: Backgrid.HeaderCell.extend({
          render: function () {
            Backgrid.HeaderCell.prototype.render.apply(this, arguments);
            this.$el.attr('title', this.column.get('label'));
            // optionally, if you use bootstrap
            this.$el.tooltip();
            return this;       
          } 
        }),
        columns: this.columns,
        collection: this.collection
      });
    } 
  })
});
```

It would be nice if `Backgrid.Header` passed its options through when constructing `Backgrid.HeaderRow`, just like `Backgrid.Grid` [does](https://github.com/wyuenho/backgrid/blob/624745c9d8049788a5aaa28e01a902b19e16e8a1/src/grid.js#L95) for footer and header.
