### ISSUE TITLE
How to: Nested Models (Again)

### ISSUE THREAD

**Issue by boldtrn** [wyuenho/backgrid#594]
Hi,

currently I am wondering how a decent way to implement a nested data model with Backgrid would look like. My current approach is working, but in my opinion it is not really straight forward.

So what I do is:
- Switched to backbone-nested
- Overwrite the render, saveOrCancel, whatEverFunction in the cell.js file.

This looks something like:
```
Backgrid.Cell.prototype.render = function () {
        this.$el.empty();
        var model = this.model;
        this.$el.text(this.formatter.fromRaw(model.get(this.column.get("name")+'.value'), model));
        this.delegateEvents();
        return this;
    }
``` 

That has to be done in quite a lot of methods. I copy the original source code and add the `+'.value'` (And add some additional functionality that comes with the nested model).

Is this really the way to go? If I want to update my Backgrid version somewhen in the future I have to recopy all the code and so on. Isn't there are more beautiful solution/possibility?

Another solution could be to store two entries in the model. One has the column name and only consists of the value. The other holds the meta data and would be called ColumnName_meta (or something like that).

**Comment by aliabdzad** [comment]
please take a look at #599 , my example may solve some of your problems ;)

**Comment by boldtrn** [comment]
@aliabdzad Thanks but no. I need to be able to access meta_data that corresponds to the current column. My current solution is that I have two columns: columnName and columnName_meta. So that I can acess the _meta for each column. However, this is obviously a dirty hack, but works for the moment ;)

**Comment by aliabdzad** [comment]
oh.my concept from your question was wrong. good luck @boldtrn

**Comment by wyuenho** [comment]
Backgrid doesn't support nested data, neither does backbone. You can do one of 2 things: 1) flatten all your data and feed that into a collection specifically used for backgrid, then propagate the change events back to the collection where you sync with the server. 2) Use a model subclass that understands dotted notation in the `get` and `set` method, specify dotted names in your column definition, and that should be it.
