### ISSUE TITLE
underscore 1.8.3

### ISSUE THREAD

**Issue by RicardoD7I** [wyuenho/backgrid#595]
I'm checking my dependencies and found that i'm using underscore 1.8.3.
I want to know if backgrid is compatible with this?

**Comment by christinedraper** [comment]
We're using underscore 1.8.3 with backgrid 0.3.5 and have not encountered any issues.

fyi, if you happen to also have picked up backbone 1.2, beware there are some significant changes from backbone 1.1. The one that caught us is that backbone 1.2 only returns a model from collection.get(id) if the idAttribute is correctly set on the collection. It used to return a model with the specified id as long as the model had some sort of id, even if the collection did not specify an idAttribute.  In particular, if you are using the select-all extension in backgrid, it may stop working unless you specify an idAttribute on the grid collection.

**Comment by qferr** [comment]
+1

**Comment by wyuenho** [comment]
@christinedraper That's awesome tips. I'll keep that in mind. Backgrid 0.3.6 has just been released and the underscore dependency has been upgraded to 1.8.3. All tests passed.

**Comment by christinedraper** [comment]
@wyuenho uenho Thanks! And thanks for releasing 0.3.6 - looking forward to trying it.
