### ISSUE TITLE
How to subclass Backgrid.Cell

### ISSUE THREAD

**Issue by marseille** [wyuenho/backgrid#600]
Hello,

I want to subclass Backgrid.Cell so that a particular piece of code is run for every Cell extended off of Backgrid.Cell.

I use basic types like String and Number, and have extended my own Cell classes for types like Date and Select.

I would like the same piece of code to run no matter what cell I use, be it my implemented cell, a Boolean cell, a URI cell, whatever.

I've tried this - 

``` javascript
Backgrid.Cell = Backgrid.Cell.extend({
  initialize: function(opts){          
    Backgrid.Cell.prototype.initialize.apply(this, arguments);
      console.log("hello");
    }        
 });      
```

Hello is never printed though. Extending the other cell types in this manner has worked. 

How do I extend and replace the functionality of Backgrid.Cell ?

**Comment by wyuenho** [comment]
You have put your `initialize` method in an infinite loop. Every Backbone class and subclass extended using Backbone's `extend` method is also a plain Javascript class. You can just directly modify the prototype of `Backgrid.Cell`.

```javascript
var super = Backgrid.Cell.prototype.initialize;
Backgrid.Cell.prototype.initialize = function (options) {
    super.apply(this, arguments);
    // do whatever you want 
}
