### ISSUE TITLE
how to edit a cell using button in Backgrid.js ?

### ISSUE THREAD

**Issue by Pavan90** [wyuenho/backgrid#606]
i have seen editing a cell can be done inline by double clicking on top of the values but in my project i need to use button on that cell and then edit it

**Comment by marti1125** [comment]
Hi @Pavan90 you can add a button like this example:

```
cell: Backgrid.Cell.extend({
	  	      className: 'custom_class',
			  render: function () {				 
				   this.$el.html('<a id="btn" data-id="'+this.model.attributes['id']+'" href="#"><i class="fa fa-check"></i></a>');
				 return this;
			  }
		  }),
```

**Comment by wyuenho** [comment]
You have access to the Column inside a cell class as well

http://backgridjs.com/misc/faq.html#how-do-i-write-a-cell-that-renders-a-button-
