### ISSUE TITLE
Is this a dead project? Any active alternatives?

### ISSUE THREAD

**Issue by jadidian** [wyuenho/backgrid#608]
Came here to find out why my `Backgrid.Extension.ClientSideFilter` is undefined... But when I saw the number of open issues and the pulse, I thought maybe this project is not active anymore... does anyone know an active alternative?

**Comment by lklepner** [comment]
It does seem reasonable to ask that a project update be posted. 

I see some maintenance PRs have been committed to master but its unclear what where the merge of the perf branch left off and what the future of the project is in general.

**Comment by excentris** [comment]
I agree. Issues and PRs are piling up. Some kind of official statement from @wyuenho would be definitely welcome. This is a great project and it would be a pity to see it die.

**Comment by jadidian** [comment]
yeah, Backgrid is a great project and is well designed, I love the way its expandable so you can add your own formatters, cells, plug-ins, it deservers appreciation, attention, contribution and all those 1870 stars... but I had a very difficult time using it in my project last week till I finally gave up after 2 days of struggling, there were too many issues I had to hack my way through
