### ISSUE TITLE
Document.Ready() before Backgrid render completes

### ISSUE THREAD

**Issue by Devtr0n** [wyuenho/backgrid#619]
Is this known-behaviour? Is there a clever way to signal that Backgrid has been rendered?

$document.ready() fires and the DOM says it is complete, but backgrid is still drawing.

Is there a way to attach an "completed" event to the Grid render? I am unsure as my Javascript skills are mediocre.

**Comment by Devtr0n** [comment]
Is it possible to incorporate jQuery.holdReady() ?

**Comment by wyuenho** [comment]
```javascript
$(document).ready(function () {
 var grid = new Backgrid.Grid({
    ...
 });
 $('.my-grid-container').append(grid.render().el);
});
```
