### ISSUE TITLE
How to get a model by passing a TR / TR-index?

### ISSUE THREAD

**Issue by dirkmoors** [wyuenho/backgrid#62]
In my use case, I want to be able to click on TR elements in the table, and somehow retrieve the associated Backbone.Model from the Grid. Since the grid does it's own sorting, I cannot rely on the underlying Backbone.Collection by asking ".get(tr_index)".
How would I retrieve the associated model then?

**Comment by Pavan90** [comment]
I had a button and used var model = $(e.target).parent().parent().data('model');

Worthable Answer nhagen

**Comment by Pavan90** [comment]
i got the answer what i am looking for !! thank you
