### ISSUE TITLE
Not able to select row when row is not editable

### ISSUE THREAD

**Issue by neel5481** [wyuenho/backgrid#620]
Hi ,

During creation of the column, we have given "editable: false" because we do not want the user to change the content of the column.
Now the issue is, when the row is not editable, we are not able to select the row because we are not able to get the event of rowfocusin and rowfocusout.

```javascript
Cols = [
          {name: 'name', label:'Name', type:'text',  editable: false, cell:'string'},
          {name: 'value', label:'Value', type:'text',  editable: false, cell:'string'}          
        ];

  var FocusableRow = Backgrid.Row.extend({
    highlightColor: "lightYellow",
    events: {
      focusin: "rowFocused",
      focusout: "rowLostFocus"
    },
    rowFocused: function() {
      this.el.style.backgroundColor = this.highlightColor;
    },
    rowLostFocus: function() {
      delete this.el.style.backgroundColor;
    }
  });

  // Initialize a new Grid instance
  var grid = this.grid = new Backgrid.Grid({
          columns: Cols,
          row: FocusableRow,
          collection: new Collection(obj)
        });
```
In above code, thought i have set the row to FocusableRow, we are not getting focus event defined above. When we remove "editable: false" then we are getting the events. How to resolve this issue ?

How to select the row when all the column is not editable ?

Thanks in Advance.

**Comment by wyuenho** [comment]
You can't use the focusin/focusout events on a table row since it's not a form control element. If you just want to change the background color, you can just use CSS' `tr:hover` selector.
