### ISSUE TITLE
Backbone.PageableCollection referenced in Backgrid.js

### ISSUE THREAD

**Issue by maephisto** [wyuenho/backgrid#624]
https://github.com/wyuenho/backgrid/blob/0.3.7/lib/backgrid.js#L2568

`if (Backbone.PageableCollection &&
        collection instanceof Backbone.PageableCollection) {`

Should this logic actually be here? Backbone.PageableCollection would only be defined or of any interest if the "backgrid-paginator" plugin is used. Otherwise will always be undefined. So why using it here in the Backgrid.js codebase ?

Thus, shouldn't it be moved in the codebase responsible with paging - the "backgrid-paginator" ?

**Comment by wyuenho** [comment]
Because the comparator is constructed outside of the backgrid-paginator extension and there's no good way to monkey patch the body of a grid instance without ending up with a mess. Providing a custom PageableBody class is also a suboptimal solution, so I've decided to use duck-typing to bake in support for PageableCollection.

**Comment by maephisto** [comment]
Thanks for the reply! 
But then, when loading Backbone with `require('backbone') //CommonJS` Backbone.PageableCollection will always be `undefined`. In order to have it defined a `require('backbone.paginator')` would also be needed. Otherwise the check above would always end up 
`if (undefiend && collection instanceof undefined) {`
Thus sorting will not work on a grid with Paginator - it will only sort the page.

In the Paginator example on the Backgrid.js website, the sorting does not work either:
http://backgridjs.com/ref/extensions/paginator.html

**Comment by wyuenho** [comment]
Sorting works fine on the example. It's only enabled on the last column. backbone.paginator is a requirement for backgrid.paginator. When you want to use pagination, you'll have to `require('backgrid.paginator')` somewhere, and supply a `PageableCollection`. Under a CommonJS environment, I don't see why you would expect PageableCollection to exist without a `require('backbone.paginator')` call.

**Comment by maephisto** [comment]
Ok, maybe I am using it wrong, but when i click on "comments" header and sort it descending it looks like this, an unsorted list
https://www.dropbox.com/s/d2woq40ht8x0a5h/Screenshot%202016-04-21%2013.51.06.png?dl=0
Tested on Chrome/OSX. 

I understand the usage of the Paginator, but in my application, somehow, Backbone.PageableCollection is always undefined. The `require('backbone')` used in the backgrid.js seems to override any previous `require('backbone.paginator')`. It only works if I update backgrid.js to also include `require('backbone.paginator')` which is of course something I don't wanna do.

Is there an example somewhere of backgrid usage in a CommonJS environment?

**Comment by wyuenho** [comment]
The partially sorted result is what Github's API returns.

I'm not sure what's going on with your requires, what you described shouldn't happen as a separate require shouldn't reload a module.
