### ISSUE TITLE
render a row on model change

### ISSUE THREAD

**Issue by djyolesal** [wyuenho/backgrid#635]
Hello,

I just started to use backgrid so apologise is my question is out of scope...

I need to render the row on model change.
 i ve trie it but i have to refresh before see the change.

please help

Thanks for your insight.

**Comment by wyuenho** [comment]
The cells are rerendered automatically, so there's not point to rerendering the row by yourself. If you want to insert a row after some model changes, you can listen to the model events on the body, and call Body.insertRow.

**Comment by djyolesal** [comment]
Can you please give me a sample code, i m a newbee in JavaScript and backgrid
