### ISSUE TITLE
[Question] how to set a column editable dynamically

### ISSUE THREAD

**Issue by marti1125** [wyuenho/backgrid#638]
```
editable: function(model){
        	console.log(this.attributes.name); //return all value about the column
        	return true;
        }
```
But I need to add a condition for return true or false that condition is about value of other column active
this.model.attributes['active']

**Comment by wyuenho** [comment]
There are a couple of ways. Depending on whether you are overriding the Column or just passing a function to the column definition. If the latter, the signature is `function(Column, Model): boolean`

**Comment by marti1125** [comment]
@wyuenho  thanks
my solution is:
```

editable: function(Column, Model){
        	var data = JSON.stringify(Column);
        	var json = JSON.parse(data);
        	if(json.active){
        		return true
        	}
        	return false;
        }
```
