### ISSUE TITLE
SelectCell - Wrong Behaviour while you are focus combobox

### ISSUE THREAD

**Issue by mihirsynoverge** [wyuenho/backgrid#652]
When we are tabbing/selecting SelectCell, First time options work fine. But after first visit on same Select Cell, Option going to autoselect to first option.

This will create very big issue when we have server side linking with backgrid.

**Comment by manishbraval** [comment]
There is logical error in the original code for retaining currently selected items of a combo. 
Replace following line in your backgrid.js file

selected: _.indexOf(selectedValues, optionValue) > -1
With
selected: (selectedValues == optionValue)

This will solve your problem.
